import { Footer } from '@/components/Footer'
import { Navbar } from '@/components/Navbar'
import { motion } from 'framer-motion'
import { Calendar, User, ArrowUpRight } from 'lucide-react'

const mockDesigns = [
  {
    id: 'abc123',
    title: 'Real-time collaborative code editor',
    author: 'Alex Chen',
    date: '2026-04-10',
    scale: '10K concurrent',
    nodes: 8,
    edges: 12,
  },
  {
    id: 'def456',
    title: 'E-commerce platform with inventory management',
    author: 'Sarah Kim',
    date: '2026-04-09',
    scale: '100K concurrent',
    nodes: 12,
    edges: 20,
  },
  {
    id: 'ghi789',
    title: 'AI-powered customer support chatbot',
    author: 'Marcus Rivera',
    date: '2026-04-08',
    scale: '1K concurrent',
    nodes: 6,
    edges: 9,
  },
  {
    id: 'jkl012',
    title: 'Social media analytics dashboard',
    author: 'Priya Patel',
    date: '2026-04-07',
    scale: '10K concurrent',
    nodes: 10,
    edges: 15,
  },
  {
    id: 'mno345',
    title: 'Healthcare appointment scheduling system',
    author: 'Jordan Lee',
    date: '2026-04-06',
    scale: '1M concurrent',
    nodes: 14,
    edges: 24,
  },
  {
    id: 'pqr678',
    title: 'Video streaming platform with CDN',
    author: 'Taylor Morgan',
    date: '2026-04-05',
    scale: '100K concurrent',
    nodes: 11,
    edges: 18,
  },
]

function DesignCard({ design, index }: { design: typeof mockDesigns[0]; index: number }) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: index * 0.08, duration: 0.4, ease: [0.16, 1, 0.3, 1] }}
      className="group relative overflow-hidden rounded-lg border border-slate-border/40 bg-obsidian-soft/60 backdrop-blur-sm p-5 transition-all hover:border-cyan-500/30 hover:bg-obsidian-soft/80"
    >
      <div className="flex items-start justify-between mb-3">
        <h3 className="text-sm font-semibold text-zinc-100 group-hover:text-white transition-colors line-clamp-2">
          {design.title}
        </h3>
        <ArrowUpRight className="h-4 w-4 text-zinc-600 group-hover:text-cyan-400 transition-colors shrink-0 ml-2" />
      </div>

      <div className="flex items-center gap-3 mb-4 text-xs text-zinc-500">
        <span className="flex items-center gap-1">
          <User className="h-3 w-3" />
          {design.author}
        </span>
        <span className="flex items-center gap-1">
          <Calendar className="h-3 w-3" />
          {new Date(design.date).toLocaleDateString()}
        </span>
      </div>

      <div className="flex items-center gap-2">
        <span className="inline-flex items-center rounded border border-cyan-500/20 bg-cyan-500/5 px-2 py-0.5 text-[10px] font-mono text-cyan-400">
          {design.scale}
        </span>
        <span className="inline-flex items-center rounded border border-slate-border/30 bg-obsidian-elevated/50 px-2 py-0.5 text-[10px] font-mono text-zinc-400">
          {design.nodes} nodes
        </span>
        <span className="inline-flex items-center rounded border border-slate-border/30 bg-obsidian-elevated/50 px-2 py-0.5 text-[10px] font-mono text-zinc-400">
          {design.edges} edges
        </span>
      </div>
    </motion.div>
  )
}

export function GalleryPage() {
  return (
    <div className="min-h-screen bg-obsidian">
      <Navbar />

      {/* Hero */}
      <div className="pt-24 pb-8 px-6">
        <div className="mx-auto max-w-5xl">
          <motion.h1
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, ease: [0.16, 1, 0.3, 1] }}
            className="mb-3 text-3xl font-bold font-display text-zinc-100"
          >
            Design Gallery
          </motion.h1>
          <motion.p
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1, duration: 0.5 }}
            className="text-sm text-zinc-400 max-w-xl"
          >
            Explore system architectures generated by the community. Click any design to view its full architecture diagram and implementation guide.
          </motion.p>
        </div>
      </div>

      {/* Grid */}
      <div className="px-6 pb-16">
        <div className="mx-auto max-w-5xl grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {mockDesigns.map((design, i) => (
            <DesignCard key={design.id} design={design} index={i} />
          ))}
        </div>
      </div>

      <Footer />
    </div>
  )
}
