import type { SystemDesign } from '@/types'

export const mockSystemDesign: SystemDesign = {
  requirements: {
    entities: ['Website', 'Template', 'User', 'Collaboration Session'],
    features: [
      'AI-powered website generation',
      'Template library',
      'Real-time collaboration',
      'Third-party integrations',
    ],
    users: 'Developers and end users',
    constraints: ['Must support 1M concurrent users'],
  },
  architecture: {
    architectureType: 'microservices',
    services: [
      {
        name: 'Website Builder Service',
        description: 'AI-powered website generation',
        tech: ['Node.js', 'LLM API'],
      },
      {
        name: 'Template Library Service',
        description: 'Template management and retrieval',
        tech: ['Node.js', 'PostgreSQL'],
      },
      {
        name: 'Authentication and Authorization Service',
        description: 'User auth, OAuth2, session management',
        tech: ['Node.js', 'JWT', 'Redis'],
      },
      {
        name: 'Real-time Collaboration Service',
        description: 'WebSockets, CRDT-based sync',
        tech: ['Socket.io', 'Yjs'],
      },
      {
        name: 'Third-Party Integration Service',
        description: 'External API connections',
        tech: ['Node.js', 'OAuth'],
      },
    ],
    database: {
      type: 'NoSQL',
      reason: 'MongoDB for flexible document storage of website templates and user data',
    },
    cache: { type: 'Redis', reason: 'Low-latency session caching and real-time state' },
    queue: { type: 'Kafka', reason: 'High-throughput event streaming for collaboration' },
  },
  frontend: {
    framework: 'React 19 with TypeScript',
    styling: 'Tailwind CSS 4.2 with shadcn/ui components',
    stateManagement: 'Zustand 5.0 for global state, React Query for server state',
    pages: [
      {
        name: 'Landing Page',
        path: '/',
        description: 'Marketing page with features and CTA',
        components: ['Navbar', 'HeroSection', 'FeatureCard', 'Footer'],
        features: ['SEO optimized', 'Responsive design', 'Animations'],
      },
      {
        name: 'Dashboard',
        path: '/dashboard',
        description: 'Main workspace for building websites',
        components: ['Sidebar', 'Canvas', 'ComponentPanel', 'Toolbar'],
        features: ['Drag-and-drop builder', 'Real-time preview', 'Component library'],
      },
      {
        name: 'Login Page',
        path: '/login',
        description: 'User authentication',
        components: ['LoginForm', 'SocialAuth', 'ForgotPasswordModal'],
        features: ['OAuth2 integration', '2FA support', 'Remember me'],
      },
      {
        name: 'Template Library',
        path: '/templates',
        description: 'Browse and select templates',
        components: ['TemplateGrid', 'FilterBar', 'TemplatePreview'],
        features: ['Search', 'Filter by category', 'Live preview'],
      },
    ],
    components: [
      {
        name: 'Navbar',
        type: 'layout',
        description: 'Top navigation bar with logo and user menu',
        props: ['user', 'onLogout'],
        state: ['isMenuOpen', 'user'],
        apiCalls: ['/api/auth/me'],
      },
      {
        name: 'Canvas',
        type: 'component',
        description: 'Main drag-and-drop canvas for website building',
        props: ['website', 'components', 'onSave'],
        state: ['selectedElement', 'elements', 'history'],
        apiCalls: ['/api/websites/:id', '/api/websites/:id/save'],
      },
      {
        name: 'ComponentPanel',
        type: 'component',
        description: 'Sidebar panel showing available components',
        props: ['categories', 'onSelect'],
        state: ['searchQuery', 'filteredComponents'],
        apiCalls: ['/api/components'],
      },
      {
        name: 'LoginForm',
        type: 'form',
        description: 'User login form with validation',
        props: ['onSuccess', 'onError'],
        state: ['email', 'password', 'isLoading', 'errors'],
        apiCalls: ['/api/auth/login'],
      },
      {
        name: 'TemplateGrid',
        type: 'component',
        description: 'Grid display of available templates',
        props: ['templates', 'onSelect'],
        state: ['page', 'filters'],
        apiCalls: ['/api/templates'],
      },
      {
        name: 'Toolbar',
        type: 'layout',
        description: 'Top toolbar with save, preview, and settings',
        props: ['onSave', 'onPreview', 'onSettings'],
        state: ['isSaving', 'canUndo', 'canRedo'],
        apiCalls: ['/api/websites/:id/save'],
      },
    ],
    layout: 'Sidebar + main canvas layout with top toolbar. Left sidebar for component library, center canvas for building, right panel for properties.',
    routing: 'React Router v6 with protected routes for dashboard and public routes for landing/login',
  },
  graph: {
    nodes: [
      {
        id: 'frontend',
        type: 'frontend',
        position: { x: 400, y: -150 },
        data: { label: 'Frontend App (React 19)' },
      },
      {
        id: 'gateway',
        type: 'gateway',
        position: { x: 100, y: 40 },
        data: { label: 'API Gateway' },
      },
      {
        id: 'builder',
        type: 'service',
        position: { x: 400, y: 40 },
        data: { label: 'Website Builder Service' },
      },
      {
        id: 'template',
        type: 'service',
        position: { x: 700, y: 40 },
        data: { label: 'Template Library Service' },
      },
      {
        id: 'realtime',
        type: 'service',
        position: { x: 100, y: 200 },
        data: { label: 'Real-time Collaboration Service' },
      },
      {
        id: 'auth',
        type: 'service',
        position: { x: 400, y: 200 },
        data: { label: 'Authentication Service' },
      },
      {
        id: 'integration',
        type: 'service',
        position: { x: 700, y: 200 },
        data: { label: 'Integration Service' },
      },
      {
        id: 'db',
        type: 'database',
        position: { x: 100, y: 380 },
        data: { label: 'NoSQL Database' },
      },
      {
        id: 'cache',
        type: 'cache',
        position: { x: 400, y: 380 },
        data: { label: 'Redis Cache' },
      },
      {
        id: 'queue',
        type: 'queue',
        position: { x: 700, y: 380 },
        data: { label: 'Kafka Queue' },
      },
      {
        id: 'external',
        type: 'external',
        position: { x: 400, y: 540 },
        data: { label: 'External Services' },
      },
    ],
    edges: [
      { id: 'e0', source: 'frontend', target: 'gateway' },
      { id: 'e1', source: 'gateway', target: 'builder' },
      { id: 'e2', source: 'gateway', target: 'template' },
      { id: 'e3', source: 'gateway', target: 'auth' },
      { id: 'e4', source: 'gateway', target: 'realtime' },
      { id: 'e5', source: 'gateway', target: 'integration' },
      { id: 'e6', source: 'builder', target: 'auth' },
      { id: 'e7', source: 'builder', target: 'cache' },
      { id: 'e8', source: 'template', target: 'db' },
      { id: 'e9', source: 'template', target: 'auth' },
      { id: 'e10', source: 'auth', target: 'cache' },
      { id: 'e11', source: 'auth', target: 'db' },
      { id: 'e12', source: 'realtime', target: 'queue' },
      { id: 'e13', source: 'realtime', target: 'cache' },
      { id: 'e14', source: 'integration', target: 'external' },
      { id: 'e15', source: 'cache', target: 'external' },
    ],
  },
  explanation: {
    architectureExplanation:
      'This full-stack architecture uses React 19 with TypeScript for the frontend, featuring a drag-and-drop website builder with real-time collaboration. The backend uses a microservices pattern with an API Gateway as the entry point. The Website Builder Service handles AI-powered generation, the Template Library manages reusable components, and the Real-time Collaboration Service enables multi-user editing via WebSockets and CRDTs.',
    apiDesign: [
      { route: '/api/auth/login', method: 'POST', description: 'User login', authentication: false, requestSchema: '{ email, password }', responseSchema: '{ token, user }', rateLimit: '10 requests per minute' },
      { route: '/api/auth/register', method: 'POST', description: 'User registration', authentication: false, requestSchema: '{ email, password, name }', responseSchema: '{ token, user }' },
      { route: '/api/auth/me', method: 'GET', description: 'Get current user', authentication: true, responseSchema: '{ user }' },
      { route: '/api/websites', method: 'POST', description: 'Create a new website', authentication: true, requestSchema: '{ name, templateId }', responseSchema: '{ website }' },
      { route: '/api/websites/:id', method: 'GET', description: 'Get a website by ID', authentication: true, responseSchema: '{ website }' },
      { route: '/api/websites/:id/save', method: 'PUT', description: 'Save website changes', authentication: true, requestSchema: '{ elements, settings }', responseSchema: '{ website }' },
      { route: '/api/templates', method: 'GET', description: 'Get template list', authentication: false, responseSchema: '{ templates, pagination }' },
      { route: '/api/templates/:id', method: 'GET', description: 'Get template details', authentication: false, responseSchema: '{ template }' },
      { route: '/api/components', method: 'GET', description: 'Get available components', authentication: false, responseSchema: '{ categories, components }' },
      { route: '/api/collaboration/:websiteId', method: 'POST', description: 'Join collaboration session', authentication: true, responseSchema: '{ sessionId, wsUrl }' },
      { route: '/api/integrations', method: 'GET', description: 'List integrations', authentication: true, responseSchema: '{ integrations }' },
      { route: '/api/integrations/:id/connect', method: 'POST', description: 'Connect integration', authentication: true, requestSchema: '{ config }', responseSchema: '{ status }' },
    ],
    scalingStrategy:
      'Horizontal scaling with Kubernetes. The API Gateway handles load balancing. Real-time collaboration uses Redis pub/sub for state sync. Kafka handles event streaming for async processing. Database uses sharding by tenant. Frontend uses CDN for static assets and code splitting.',
    tradeOffs: [
      'Microservices increase operational complexity',
      'Real-time collaboration requires careful conflict resolution',
      'Higher infrastructure costs for small deployments',
      'Requires robust monitoring and observability',
    ],
  },
}
